#!/usr/bin/env python3

import os
import signal
import re
import sys
import shutil
import subprocess
import time
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor, TimeoutError

# for error lookup:
import builtins

try:
    ROOT_DIR = next(p for p in Path(__file__).parents if (p / ".git").exists())
except StopIteration:
    raise RuntimeError("Could not find root directory")

COL_FAINT = "\033[2m"
COL_ERR = "\033[91m"
COL_OK = "\033[92m"
COL_WARN = "\033[93m"
COL_INFO = "\033[94m"
COL_END = "\033[0m"

START_VAR_RE: re.Pattern = re.compile(r"__start_[0-9a-fA-F]{16}__")

COMPILER_BUILD_DIR = ROOT_DIR / "dist"
if not COMPILER_BUILD_DIR.exists():
    COMPILER_BUILD_DIR = ROOT_DIR / "boot"

sys.path.insert(0, str(COMPILER_BUILD_DIR))
from cputh.compile.compiler import compile_cputh_to_py
import cputh.exceptions.errors as cputh_errors

FIXTURES_DIR = ROOT_DIR / "tests" / "fixtures"

QUESTIONS_DIR = FIXTURES_DIR / "questions"
MARKING_DIR = FIXTURES_DIR / "marking"
DIST_DIR = FIXTURES_DIR / "dist"

WORKING_TIME_PER_QUESTION = 0.050  # max seconds per question

def get_exc_type_from_str(typ_name: str) -> type[Exception]:
    typ = getattr(builtins, typ_name, None)
    if not typ:
        typ = getattr(cputh_errors, typ_name, None)
    if not typ:
        raise ValueError(f"{typ_name}: no such type")
    if not isinstance(typ, type) or not issubclass(typ, Exception):
        raise ValueError(f"{typ_name}: not a type")
    return typ

def run_cmd(argv: list[str], cwd: Path | str = ".") -> subprocess.CompletedProcess:
    return subprocess.run(argv, check=True, cwd=cwd)

def _warmup_worker():
    """A dummy function to force the OS process to spawn.
    Prevents the tax from using a ProcessPoolExecutor for the first time."""
    return True

class Marker:
    def __init__(self) -> None:
        self.refresh_executor()

    def refresh_executor(self) -> None:
        self.executor = ProcessPoolExecutor(max_workers=1)
        future = self.executor.submit(_warmup_worker)
        future.result()

    def normalise_answer(self, ans: str) -> str:
        """Normalise variable names like __start_1234567890abcdef__
        that are randomly generated by the compiler."""
        # THIS WILL BREAK ON START VARS INSIDE STRINGS

        # set the salt to a normalised placeholder
        ans = START_VAR_RE.sub("__start_var__", ans)

        # remove trailing whitespace
        ans = "\n".join(line.rstrip() for line in ans.splitlines())

        return ans

    def mark(self, ans: str, correct_ans: str) -> int:
        """Returns 1 for correct answers, 0 otherwise."""
        ans_norm = self.normalise_answer(ans)
        correct_ans_norm = self.normalise_answer(correct_ans)
        return 1 if ans_norm == correct_ans_norm else 0

    def run_positive_test(self, question_fp: Path, dist_fp: Path) -> int:
        """Run a positive test and return 1 if passed, else 0.
        Raises FileNotFoundError if the marking key is missing.
        Raises TimeoutError if the compiler takes too long."""

        rel_fp = question_fp.relative_to(QUESTIONS_DIR)
        display_fp = question_fp.relative_to(ROOT_DIR)
        marking_file = MARKING_DIR / rel_fp.with_suffix(".py")

        if not marking_file.exists():
            raise FileNotFoundError(f"Missing marking file at '{marking_file}'")

        q_cputh = question_fp.read_text()
        correct_ans = marking_file.read_text()

        t_i = time.time()

        try:
            future = self.executor.submit(compile_cputh_to_py, q_cputh)
            ans = future.result(timeout=WORKING_TIME_PER_QUESTION)
            t_f = time.time()

            dist_fp.parent.mkdir(parents=True, exist_ok=True)
            with open(dist_fp, "w") as file:
                file.write(ans)

            mark = self.mark(ans=ans, correct_ans=correct_ans)

            if mark:
                print_pass(f"Question '{display_fp}' marked as correct.", t_i=t_i, t_f=t_f)
                return 1

            print_fail(f"Question '{display_fp}' marked as incorrect.", t_i=t_i, t_f=t_f)
            return 0

        except TimeoutError:
            t_f = time.time()

            try:
                # self.executor._processes is a dict tracking active child PIDs
                pids = list(self.executor._processes.keys())
                for pid in pids:
                    # Send a hard terminate signal at the OS level
                    os.kill(pid, signal.SIGKILL)
            except Exception:
                pass  # Already dead or inaccessible

            # Forcefully kill the compiler process
            self.executor.shutdown(wait=False, cancel_futures=True)
            self.refresh_executor()

            print_fail(
                f"Timeout in positive test '{display_fp}':\n"
                f"    Compiler exceeded the maximum allotted time ({WORKING_TIME_PER_QUESTION}s).\n"
                f"    Process forcefully terminated.",
                t_i=t_i, t_f=t_f
            )
            return 0

        except Exception as e:
            # compiler crashed when it should have produced runnable code -> penalise!
            t_f = time.time()
            str_e = str(e)
            print_fail(
                f"Exception in positive test '{display_fp}':\n"
                f"    {type(e).__name__}{f": {str_e}" if str_e else ""}",
                t_i=t_i, t_f=t_f
            )
            return 0

    def run_negative_test(self, question_fp: Path, dist_fp: Path) -> int:
        """Run a negative test and return 1 if passed, else 0.
        Raises TimeoutError if the compiler takes too long."""

        # Parse the right exception name
        # e.g. splits "# TEST: RAISE: SyntaxError" into ["# TEST: RAISE", "SyntaxError"]
        display_fp = question_fp.relative_to(ROOT_DIR)

        q_cputh = question_fp.read_text()
        first_line = q_cputh.splitlines()[0] if q_cputh else ""
        parts = [p.strip() for p in first_line.split(":", 2)]

        if len(parts) == 2:
            # bare `TEST: RAISE`
            exc_type = Exception
        elif len(parts) != 3:
            # invalid test header
            raise RuntimeError(f"Invalid test header in file: '{display_fp}'.")
        else:
            exc_type = get_exc_type_from_str(parts[2])

        t_i = time.time()

        try:
            # If it compiles, 0 marks because it was supposed to raise
            future = self.executor.submit(compile_cputh_to_py, q_cputh)
            ans = future.result(timeout=WORKING_TIME_PER_QUESTION)
            t_f = time.time()

            dist_fp.parent.mkdir(parents=True, exist_ok=True)
            with open(dist_fp, "w") as file:
                file.write(ans)

            print_fail(f"Negative test completed without exception: '{display_fp}'.", t_i=t_i, t_f=t_f)
            return 0

        except TimeoutError:
            t_f = time.time()

            try:
                # self.executor._processes is a dict tracking active child PIDs
                pids = list(self.executor._processes.keys())
                for pid in pids:
                    # Send a hard terminate signal at the OS level
                    os.kill(pid, signal.SIGKILL)
            except Exception:
                pass  # Already dead or inaccessible

            # Forcefully kill the compiler process
            self.executor.shutdown(wait=False, cancel_futures=True)
            self.refresh_executor()

            print_fail(
                f"Timeout in negative test '{display_fp}':\n"
                f"    Compiler exceeded the maximum allotted time ({WORKING_TIME_PER_QUESTION}s)."
                f"    Process forcefully terminated.",
                t_i=t_i, t_f=t_f
            )
            return 0

        except Exception as e:
            t_f = time.time()

            # Only award the mark if it raised the right Exception type
            str_e = str(e)
            exc_msg = f"{type(e).__name__}{f": {str_e}" if str_e else ""}"

            if isinstance(e, exc_type):
                print_pass(
                    f"Exception raised in negative test:\n"
                    f"    {exc_msg}",
                    t_i=t_i, t_f=t_f
                )
                return 1

            print_fail(
                f"Incorrect exception type raised in negative test:\n"
                f"    Correct: {exc_type.__name__}\n"
                f"    Actual:  {exc_msg}",
                t_i=t_i, t_f=t_f
            )
            return 0

def _format_time(t_i: float, t_f: float) -> str:
    dt_ms = 1_000 * (t_f - t_i)
    return f"{COL_FAINT}({dt_ms:.3f} ms){COL_END}"

def print_pass(s: str, *, t_i: float, t_f: float) -> None:
    dt = t_f - t_i
    print(f"  {COL_OK}Pass {COL_END}{_format_time(t_i, t_f)}: {s}")

def print_fail(s: str, *, t_i: float, t_f: float) -> None:
    dt = t_f - t_i
    print(f"  {COL_ERR}Fail {COL_END}{_format_time(t_i, t_f)}: {s}")

class Exam:
    def __init__(self) -> None:
        self.question_paths: list[Path] = sorted(QUESTIONS_DIR.rglob("*.cputh"))
        self.marker = Marker()

    def run(self) -> int:
        """Return an exit code: 0 if tests passed, 1 otherwise."""
        print(f"Starting exam...")
        print(f"  {COL_INFO}{WORKING_TIME_PER_QUESTION * 1_000:.3f} ms{COL_END} per question")
        print()

        score = 0
        total_marks = 0

        for question_fp in self.question_paths:
            try:
                # file for the compiler to write answers to for later review if needed
                rel_fp = question_fp.relative_to(QUESTIONS_DIR)
                display_fp = question_fp.relative_to(ROOT_DIR)
                dist_fp = DIST_DIR / rel_fp.with_suffix(".py")

                print(f"Question: {COL_INFO}'{display_fp}'{COL_END}")

                mark = 0  # default

                if (q_cputh := question_fp.read_text()):
                    first_line = q_cputh.splitlines()[0].strip()
                else:
                    first_line = ""

                if first_line.startswith("# TEST: RAISE"):
                    mark = self.marker.run_negative_test(question_fp=question_fp, dist_fp=dist_fp)
                else:
                    mark = self.marker.run_positive_test(question_fp=question_fp, dist_fp=dist_fp)

                total_marks += 1
                score += mark
            except FileNotFoundError:
                # missing marking key
                print(f"  {COL_WARN}Warning{COL_END}: No marking file found for {COL_WARN}'{question_fp.relative_to(ROOT_DIR)}'{COL_END}, skipping.", file=sys.stderr)

                # Then we skip incrementing total_marks so as not to penalise the compiler.

        # show results
        print("\nTests completed.")

        if not total_marks:
            print("  No questions were marked.")
            return 0

        passed = (score == total_marks)
        result_str = f"{COL_OK}PASS{COL_END}" if passed else f"{COL_ERR}FAIL{COL_END}"
        frac = score / total_marks

        print(f"  Result: {result_str} ({score} / {total_marks} - {frac:.2%})")

        return 0 if passed else 1

def main():
    # Clean up any previous tests
    if DIST_DIR.exists() and DIST_DIR.is_dir() and "fixtures" in DIST_DIR.parts:
        shutil.rmtree(DIST_DIR)

    # Recreate the blank directory so the rest of the script has a clean slate
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    exam = Exam()
    exitcode = exam.run()
    return exitcode

if __name__ == "__main__":
    exitcode = main()
    sys.exit(exitcode)
