#!/usr/bin/env python3

import re
import sys
import shutil
import subprocess
from pathlib import Path

# for error lookup:
import builtins

try:
    ROOT_DIR = next(p for p in Path(__file__).parents if (p / ".git").exists())
except StopIteration:
    raise RuntimeError("Could not find root directory")

COL_ERR = "\033[91m"
COL_OK = "\033[92m"
COL_WARN = "\033[93m"
COL_INFO = "\033[94m"
COL_END = "\033[0m"

START_VAR_RE: re.Pattern = re.compile(r"__start_[0-9a-fA-F]{16}__")

TEST_DIST_DIR = ROOT_DIR / "dist"
sys.path.insert(0, str(TEST_DIST_DIR))
from cputh.compile.compiler import compile_cputh_to_py
import cputh.exceptions.errors as cputh_errors

FIXTURES_DIR = ROOT_DIR / "tests" / "fixtures"

QUESTIONS_DIR = FIXTURES_DIR / "questions"
MARKING_DIR = FIXTURES_DIR / "marking"
DIST_DIR = FIXTURES_DIR / "dist"

def get_exc_type_from_str(typ_name: str) -> type[Exception]:
    typ = getattr(builtins, typ_name, None)
    if not typ:
        typ = getattr(cputh_errors, typ_name, None)
    if not typ:
        raise ValueError(f"{typ_name}: no such type")
    if not isinstance(typ, type) or not issubclass(typ, Exception):
        raise ValueError(f"{typ_name}: not a type")
    return typ

def run_cmd(argv: list[str], cwd: Path | str = ".") -> subprocess.CompletedProcess:
    return subprocess.run(argv, check=True, cwd=cwd)

class Marker:
    def normalise_answer(self, ans: str) -> str:
        """Normalise variable names like __start_1234567890abcdef__
        that are randomly generated by the compiler."""
        # THIS WILL BREAK ON START VARS INSIDE STRINGS

        # set the salt to all 0s
        ans = START_VAR_RE.sub("__start_0000000000000000__", ans)

        # remove trailing whitespace
        ans = "\n".join(line.rstrip() for line in ans.splitlines())

        return ans

    def mark(self, ans: str, correct_ans: str) -> int:
        """Returns 1 for correct answers, 0 otherwise."""
        ans_norm = self.normalise_answer(ans)
        correct_ans_norm = self.normalise_answer(correct_ans)
        return 1 if ans_norm == correct_ans_norm else 0

def print_pass(s: str) -> None:
    print(f"  {COL_OK}Pass{COL_END}: {s}")

def print_fail(s: str) -> None:
    print(f"  {COL_ERR}Fail{COL_END}: {s}")

class Exam:
    def __init__(self) -> None:
        self.question_paths: list[Path] = sorted(QUESTIONS_DIR.rglob("*.cputh"))
        self.marker = Marker()

    def run(self) -> int:
        """Return an exit code: 0 if tests passed, 1 otherwise."""
        score = 0
        total_marks = 0

        for question_fp in self.question_paths:
            rel_fp = question_fp.relative_to(QUESTIONS_DIR)
            display_fp = question_fp.relative_to(ROOT_DIR)

            # file for the compiler to write answers to for later review if needed
            dist_fp = DIST_DIR / rel_fp.with_suffix(".py")

            print(f"Question: {COL_INFO}'{display_fp}'{COL_END}")

            q_cputh = question_fp.read_text()
            first_line = q_cputh.splitlines()[0] if q_cputh else ""
            mark = 0  # default

            if first_line.startswith("# TEST: RAISE"):
                # Parse the right exception name
                # e.g. splits "# TEST: RAISE: SyntaxError" into ["# TEST: RAISE", "SyntaxError"]
                parts = [p.strip() for p in first_line.split(":", 2)]

                if len(parts) == 2:
                    # bare TEST: RAISE
                    exc_type = Exception
                elif len(parts) != 3:
                    # invalid test header
                    raise RuntimeError(f"Invalid test header in file: '{display_fp}'.")
                else:
                    exc_type = get_exc_type_from_str(parts[2])

                try:
                    # If it compiles, 0 marks because it was supposed to raise
                    compile_cputh_to_py(q_cputh)

                    print_fail(f"Negative test completed without exception: '{display_fp}'.")
                except Exception as e:
                    # Only award the mark if it raised the right Exception type
                    str_e = str(e)
                    exc_msg = f"{type(e).__name__}{f": {str_e}" if str_e else ""}"
                    if isinstance(e, exc_type):
                        mark = 1
                        print_pass(
                            f"Exception raised in negative test:\n"
                            f"    {exc_msg}"
                        )
                    else:
                        print_fail(
                            f"Incorrect exception type raised in negative test:\n"
                            f"    Correct: {exc_type.__name__}\n"
                            f"    Actual:  {exc_msg}"
                        )

            else:
                marking_file = MARKING_DIR / rel_fp.with_suffix(".py")

                if not marking_file.exists():
                    print(f"  {COL_WARN}Warning{COL_END}: No marking file found for {COL_WARN}'{display_fp}'{COL_END}, skipping.", file=sys.stderr)
                    continue

                try:
                    correct_ans = marking_file.read_text()
                    ans = compile_cputh_to_py(q_cputh)

                    dist_fp.parent.mkdir(parents=True, exist_ok=True)
                    with open(dist_fp, "w") as file:
                        file.write(ans)

                    mark = self.marker.mark(ans=ans, correct_ans=correct_ans)

                    if mark:
                        print_pass(f"Question '{display_fp}' marked as correct.")
                    else:
                        print_fail(f"Question '{display_fp}' marked as incorrect.")
                except Exception as e:
                    # compiler crashed when it should have produced runnable code -> penalise!
                    # we just don't set the `mark` variable to 1
                    str_e = str(e)
                    print_fail(
                        f"Exception in positive test '{display_fp}':\n"
                        f"    {type(e).__name__}{f": {str_e}" if str_e else ""}"
                    )

            total_marks += 1
            score += mark

        # show results
        print("\nTests completed.")

        if not total_marks:
            print("  No questions were marked.")
            return 0

        passed = (score == total_marks)
        result_str = f"{COL_OK}PASS{COL_END}" if passed else f"{COL_ERR}FAIL{COL_END}"
        frac = score / total_marks

        print(f"  Result: {result_str} ({score} / {total_marks} - {frac:.2%})")

        return 0 if passed else 1

def main():
    # Clean up any previous tests
    if DIST_DIR.exists() and DIST_DIR.is_dir() and "fixtures" in DIST_DIR.parts:
        shutil.rmtree(DIST_DIR)

    # Recreate the blank directory so the rest of the script has a clean slate
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    exam = Exam()
    exitcode = exam.run()
    return exitcode

if __name__ == "__main__":
    exitcode = main()
    sys.exit(exitcode)
